language: cpp
compiler: gcc
addons: 
    apt:
        packages:
            - libboost-test-dev
            - libhdf5-serial-dev
            - openmpi-bin
os:
    - linux
install: true
script: make && make test
