language: cpp
os: linux
#Don't use gcc as the default gcc on travis is 4.6, too old for C++11.
compiler: clang
addons: 
    apt:
        packages:
            - libboost-test-dev
            - libhdf5-serial-dev
env:
    - OMPI_CXX=clang++
install: true
script: make && make test
