language: cpp
os: linux
compiler: gcc
addons: 
    apt:
        packages:
            - libboost-test-dev
            - libhdf5-serial-dev
            - openmpi-bin
install: true
script: make && make test
